BEGIN TRANSACTION;
DELETE FROM companies;
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΑΛΦΑ ΒΗΤΑ ΒΑΣΙΛΟΠΟΥΛΟΣ ΜΟΝΟΠΡΟ', 'ΑΒ Βασιλόπουλος', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΔΙΑΜΑΝΤΗΣ ΜΑΣΟΥΤΗΣ ΑΕ ΣΟΥΠΕΡ Μ', 'μασούτης', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΣΟΥΠΕΡ ΜΑΡΚΕΤ ΕΓΝΑΤΙΑ ΑΕ', 'Discount Markt', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΕΛΛΗΝΙΚΕΣ ΥΠΕΡΑΓΟΡΕΣ ΣΚΛΑΒΕΝΙΤ', 'Σκλαβενίτης', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΛΙΝΤΛ ΕΛΛΑΣ ΚΑΙ ΣΙΑ ΟΜΟΡΡΥΘΜΗ', 'LIDL', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΜΕΤΡΟ ΑΝΩΝΥΜΟΣ ΕΜΠΟΡΙΚΗ ΚΑΙ ΒΙ', 'My market', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΠΕΝΤΕ ΑΕ ΑΝΩΝΥΜΗ ΕΜΠΟΡΙΚΗ ΕΤΑΙ', 'Γαλαξίας', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('BAZAAR ΑΝΩΝΥΜΗ ΨΥΚΤΙΚΗ ΒΙΟΜΗΧΑ', 'Bazaar', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΤΕΡΤΙΒΑΝΙΔΗΣ ΧΑΡΙΛ', 'ΤΕΡΤΙΒΑΝΙΔΗΣ', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΓΚΕΚΤΣΙΑΝ ΑΡΣΕΝ', 'Prime Market Mini Market', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΗΛΙΑΔΗΣ ΙΩΑΚΕ', 'Καφεκοπτείο Ηλιάδη', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΧΟΝΔΡΑΝΤΩΝΗΣ ΚΩΝΣΤ', 'Φούρνος Χονδραντώνης', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΑΣΛΑΝΙΔΗΣ ΙΩΑΝΝ', 'Φούρνος Ασλανίδης Breda', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΜΙΝΔΗΣ ΚΩΝΣΤ', 'Ζαχαροπλαστείο Φίνο', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΤΣΙΛΙΓΚΕΡΙΔΟΥ ΚΑΙ ΣΙΑ ΟΕ', 'Ιχθυοπωλείο Τσιλιγκερίδου', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΧΟΥΛΙΑΡΑΣ ΠΡΟΔΡ', 'Ιχθυοπωλείο Χουλιάρας', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΚΥΡΤΣΙΟΣ ΑΠΟΣΤΟΛΟΣ ΤΣΙΑΠΑΝΙΤ', 'Κρεοπωλείο Φάρμα Κύρτσιος', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΜΠΑΡΜΠΑΡΟΥΣΗΣ ΣΩΤΗΡ', 'Οπωροπωλείο Μπαρμπαρούσης', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΔΗΜΗΤΡΙΟΥ ΙΩΑΝΝ', 'Παντοπωλείο Δημητρίου', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΓΩΤΑΣ ΓΕΩΡΓ', 'Περίπτερο Γώτας', 'Καθημερινά Ψώνια');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΤΣΑΚΙΡΙΔΗΣ ΙΣΑΑΚ', 'Στο Άψε Ψήσε', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΜΑΓΕΙΡΕΙΑ ΣΤΑΓΚΙΔΗ ΕΕ', 'Μαγειρείο-Καντίνα Σταγκίδης', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΧΧ ΚΡΕΑΤΟΣΚΕΥΑΣΜΑΤΑ ΚΑΙ ΣΙΑ Ε', 'Χρήστος Γυράδικο', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΓΕΣΑΓΙΑΝ ΟΒΑΝΝ', 'Θράκα 18', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΚΑΡΑΤΖΟΓΛΟΥ ΕΛΕΥΘ', 'Vitro', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΦΩΤΕΙΝΗ ΤΡΥΠΤΣΙΑ ΧΡΗΣΤΟΣ ΓΚΟΛΦ', 'Το Κάτι Άλλο', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('FIVE PLUS Ι Κ Ε', 'ΓΡΝ', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΣΑΟΥΛΙΔΗΣ Ν ΟΥΖΟΥΝΗΣ Ι ΟΕ', 'Από την σχάρα στην λαδόκολλα', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('Β ΓΕΩΡΓΙΟΥ 24 ΕΣΤΙΑΣΗ Ε Ε', 'Φάτε Σκάστε', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΣΤΕΦΑΝΟΥ ΠΑΡΘΕ', 'Porkito', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΙΟΡΔΑΝΙΔΗΣ ΠΑΝΑΓ', 'Pizza Jordani', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΚΟΥΚΛΗΣ Δ ΚΑΙ Σ ΟΕ', 'Ταβέρνα Κούκλης', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('VEN 54 ΥΠΗΡΕΣΙΕΣ ΕΣΤΙΑΣΗΣ ΙΔΙ', 'Ven54 Pizza', 'Εστίαση');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΛΟΓΙΣΜΙΚΗ ΕΠΕ', 'Ticket Services', 'Ψυχαγωγία');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ODEON ENTERTAINMENT MANAGEMENT', 'Odeon', 'Ψυχαγωγία');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΣΚΡΟΥΤΖ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ ΥΠΗΡΕΣΙΕΣ ΔΙΑΔΙΚΤΥΟΥ', 'skroutz', 'E-commerce');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('DIGITAL SIMPLY ΟΕ', 'metabook', 'E-commerce');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΤΖΕΒΕΛΕΚΙΔΗΣ ΑΕ ΕΜΠΟΡΙΑ ΗΛΕΚΤΡ', 'Electromarkt', 'E-commerce');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΜΥΡΤΟ ΜΑΡΙΟΥΣ ΚΑΙ ΣΙΑ ΕΕ', 'Κομμωτήριο Old School Barber Shop', 'Υπηρεσίες Αισθητικής');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΨΩΜΑ ΒΑΣΙΛ', 'Κομμωτήριο Hair Club', 'Υπηρεσίες Αισθητικής');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ ΜΕΤΑΦΟΡΩΝ ΕΚ', 'Shell', 'Καύσιμα');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΑΦΟΙ ΚΑΛΛΙΑΡΙΔΗ ΟΕ', 'ΕΚΟ', 'Καύσιμα');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('Κ ΣΙΔΗΡΟΠΟΥΛΟΥ ΚΑΙ Η Ε ΣΙΔΗΡ', 'BP', 'Καύσιμα');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('Ι ΝΑΚΟΠΟΥΛΟΥ ΣΙΑ Ε Ε', 'Φαρμακείο Νακοπούλου', 'Ιατροφαρμακευτικά');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΝΙΚΟΛΑΙΔΗΣ ΜΙΛΤΙ', 'Φαρμακείο Νικολαΐδης', 'Ιατροφαρμακευτικά');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΠΑΠΑΡΗ ΟΛΥΜΠ', 'Φαρμακείο Πάπαρη', 'Ιατροφαρμακευτικά');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΜΠΟΖΑΣ ΣΤΕΡΓ', 'Οφθαλμίατρος Μπόζας', 'Ιατροφαρμακευτικά');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΦΑΡΜΑΚΕΙΟ ΧΡΗΣΤΟΥ ΠΟΝΤΙΚΗ ΚΑΙ', 'Drug-store.gr', 'Ιατροφαρμακευτικά');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('ΠΑΥΛΙΔΗΣ TILES ΜΟΝΟΠΡΟΣΩΠΗ ΙΔΙ', 'Παυλίδης', 'Οικιακά Είδη');
INSERT INTO companies (company_name, discrete_title, category) VALUES ('WENG YUEQI', 'WENG YUEQI', 'Ρούχα - Παπούτσια');
COMMIT;

