INSERT INTO companies VALUES ('ΑΛΦΑ ΒΗΤΑ ΒΑΣΙΛΟΠΟΥΛΟΣ ΜΟΝΟΠΡΟ', 'ΑΒ Βασιλόπουλος', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΔΙΑΜΑΝΤΗΣ ΜΑΣΟΥΤΗΣ ΑΕ ΣΟΥΠΕΡ Μ', 'μασούτης', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΣΟΥΠΕΡ ΜΑΡΚΕΤ ΕΓΝΑΤΙΑ ΑΕ', 'Discount Markt', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΕΛΛΗΝΙΚΕΣ ΥΠΕΡΑΓΟΡΕΣ ΣΚΛΑΒΕΝΙΤ', 'Σκλαβενίτης', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΛΙΝΤΛ ΕΛΛΑΣ ΚΑΙ ΣΙΑ ΟΜΟΡΡΥΘΜΗ', 'LIDL', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΜΕΤΡΟ ΑΝΩΝΥΜΟΣ ΕΜΠΟΡΙΚΗ ΚΑΙ ΒΙ', 'My market', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΠΕΝΤΕ ΑΕ ΑΝΩΝΥΜΗ ΕΜΠΟΡΙΚΗ ΕΤΑΙ', 'Γαλαξίας', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('BAZAAR ΑΝΩΝΥΜΗ ΨΥΚΤΙΚΗ ΒΙΟΜΗΧΑ', 'Bazaar', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΤΕΡΤΙΒΑΝΙΔΗΣ ΧΑΡΙΛ', 'ΤΕΡΤΙΒΑΝΙΔΗΣ', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΓΚΕΚΤΣΙΑΝ ΑΡΣΕΝ', 'Prime Market Mini Market', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΗΛΙΑΔΗΣ ΙΩΑΚΕ', 'Καφεκοπτείο Ηλιάδη', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΧΟΝΔΡΑΝΤΩΝΗΣ ΚΩΝΣΤ', 'Φούρνος Χονδραντώνης', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΑΣΛΑΝΙΔΗΣ ΙΩΑΝΝ', 'Φούρνος Ασλανίδης Breda', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΜΙΝΔΗΣ ΚΩΝΣΤ', 'Ζαχαροπλαστείο Φίνο', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΤΣΙΛΙΓΚΕΡΙΔΟΥ ΚΑΙ ΣΙΑ ΟΕ', 'Ιχθυοπωλείο Τσιλιγκερίδου', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΧΟΥΛΙΑΡΑΣ ΠΡΟΔΡ', 'Ιχθυοπωλείο Χουλιάρας', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΚΥΡΤΣΙΟΣ ΑΠΟΣΤΟΛΟΣ ΤΣΙΑΠΑΝΙΤ', 'Κρεοπωλείο Φάρμα Κύρτσιος', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΜΠΑΡΜΠΑΡΟΥΣΗΣ ΣΩΤΗΡ', 'Οπωροπωλείο Μπαρμπαρούσης', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΔΗΜΗΤΡΙΟΥ ΙΩΑΝΝ', 'Παντοπωλείο Δημητρίου', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΓΩΤΑΣ ΓΕΩΡΓ', 'Περίπτερο Γώτας', 'Καθημερινά Ψώνια');
INSERT INTO companies VALUES ('ΤΣΑΚΙΡΙΔΗΣ ΙΣΑΑΚ', 'Στο Άψε Ψήσε', 'Εστίαση');
INSERT INTO companies VALUES ('ΜΑΓΕΙΡΕΙΑ ΣΤΑΓΚΙΔΗ ΕΕ', 'Μαγειρείο-Καντίνα Σταγκίδης', 'Εστίαση');
INSERT INTO companies VALUES ('ΧΧ ΚΡΕΑΤΟΣΚΕΥΑΣΜΑΤΑ ΚΑΙ ΣΙΑ Ε', 'Χρήστος Γυράδικο', 'Εστίαση');
INSERT INTO companies VALUES ('ΓΕΣΑΓΙΑΝ ΟΒΑΝΝ', 'Θράκα 18', 'Εστίαση');
INSERT INTO companies VALUES ('ΚΑΡΑΤΖΟΓΛΟΥ ΕΛΕΥΘ', 'Vitro', 'Εστίαση');
INSERT INTO companies VALUES ('ΦΩΤΕΙΝΗ ΤΡΥΠΤΣΙΑ ΧΡΗΣΤΟΣ ΓΚΟΛΦ', 'Το Κάτι Άλλο', 'Εστίαση');
INSERT INTO companies VALUES ('FIVE PLUS Ι Κ Ε', 'ΓΡΝ', 'Εστίαση');
INSERT INTO companies VALUES ('ΣΑΟΥΛΙΔΗΣ Ν ΟΥΖΟΥΝΗΣ Ι ΟΕ', 'Από την σχάρα στην λαδόκολλα', 'Εστίαση');
INSERT INTO companies VALUES ('Β ΓΕΩΡΓΙΟΥ 24 ΕΣΤΙΑΣΗ Ε Ε', 'Φάτε Σκάστε', 'Εστίαση');
INSERT INTO companies VALUES ('ΣΤΕΦΑΝΟΥ ΠΑΡΘΕ', 'Porkito', 'Εστίαση');
INSERT INTO companies VALUES ('ΙΟΡΔΑΝΙΔΗΣ ΠΑΝΑΓ', 'Pizza Jordani', 'Εστίαση');
INSERT INTO companies VALUES ('ΚΟΥΚΛΗΣ Δ ΚΑΙ Σ ΟΕ', 'Ταβέρνα Κούκλης', 'Εστίαση');
INSERT INTO companies VALUES ('VEN 54 ΥΠΗΡΕΣΙΕΣ ΕΣΤΙΑΣΗΣ ΙΔΙ', 'Ven54 Pizza', 'Εστίαση');
INSERT INTO companies VALUES ('ΛΟΓΙΣΜΙΚΗ ΕΠΕ', 'Ticket Services', 'Ψυχαγωγία');
INSERT INTO companies VALUES ('ODEON ENTERTAINMENT MANAGEMENT', 'Odeon', 'Ψυχαγωγία');
INSERT INTO companies VALUES ('ΣΚΡΟΥΤΖ ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ ΥΠΗΡΕΣΙΕΣ ΔΙΑΔΙΚΤΥΟΥ', 'skroutz', 'E-commerce');
INSERT INTO companies VALUES ('DIGITAL SIMPLY ΟΕ', 'metabook', 'E-commerce');
INSERT INTO companies VALUES ('ΤΖΕΒΕΛΕΚΙΔΗΣ ΑΕ ΕΜΠΟΡΙΑ ΗΛΕΚΤΡ', 'Electromarkt', 'E-commerce');
INSERT INTO companies VALUES ('ΜΥΡΤΟ ΜΑΡΙΟΥΣ ΚΑΙ ΣΙΑ ΕΕ', 'Κομμωτήριο Old School Barber Shop', 'Υπηρεσίες Αισθητικής');
INSERT INTO companies VALUES ('ΨΩΜΑ ΒΑΣΙΛ', 'Κομμωτήριο Hair Club', 'Υπηρεσίες Αισθητικής');
INSERT INTO companies VALUES ('ΑΝΩΝΥΜΟΣ ΕΤΑΙΡΕΙΑ ΜΕΤΑΦΟΡΩΝ ΕΚ', 'Shell', 'Καύσιμα');
INSERT INTO companies VALUES ('ΑΦΟΙ ΚΑΛΛΙΑΡΙΔΗ ΟΕ', 'ΕΚΟ', 'Καύσιμα');
INSERT INTO companies VALUES ('Κ ΣΙΔΗΡΟΠΟΥΛΟΥ ΚΑΙ Η Ε ΣΙΔΗΡ', 'BP', 'Καύσιμα');
INSERT INTO companies VALUES ('Ι ΝΑΚΟΠΟΥΛΟΥ ΣΙΑ Ε Ε', 'Φαρμακείο Νακοπούλου', 'Ιατροφαρμακευτικά');
INSERT INTO companies VALUES ('ΝΙΚΟΛΑΙΔΗΣ ΜΙΛΤΙ', 'Φαρμακείο Νικολαΐδης', 'Ιατροφαρμακευτικά');
INSERT INTO companies VALUES ('ΠΑΠΑΡΗ ΟΛΥΜΠ', 'Φαρμακείο Πάπαρη', 'Ιατροφαρμακευτικά');
INSERT INTO companies VALUES ('ΜΠΟΖΑΣ ΣΤΕΡΓ', 'Οφθαλμίατρος Μπόζας', 'Ιατροφαρμακευτικά');
INSERT INTO companies VALUES ('ΦΑΡΜΑΚΕΙΟ ΧΡΗΣΤΟΥ ΠΟΝΤΙΚΗ ΚΑΙ', 'Drug-store.gr', 'Ιατροφαρμακευτικά');
INSERT INTO companies VALUES ('ΠΑΥΛΙΔΗΣ TILES ΜΟΝΟΠΡΟΣΩΠΗ ΙΔΙ', 'Παυλίδης', 'Οικιακά Είδη');
INSERT INTO companies VALUES ('WENG YUEQI', 'WENG YUEQI', 'Ρούχα - Παπούτσια');